import type { Destination, Guide, Review, TripRequest } from "./types";
import { destinationImage, keralaImages } from "./images";

export const destinations: Destination[] = [
  {
    id: "1",
    name: "Trivandrum",
    slug: "trivandrum",
    image: destinationImage("trivandrum"),
    description: "Temples, beaches, and backwaters at Kerala's capital",
    guideCount: 24,
    highlights: ["Kovalam Beach", "Padmanabhaswamy Temple", "Varkala Cliffs"],
  },
  {
    id: "2",
    name: "Munnar",
    slug: "munnar",
    image: destinationImage("munnar"),
    description: "Rolling tea plantations and misty mountain trails",
    guideCount: 18,
    highlights: ["Tea Gardens", "Eravikulam", "Top Station"],
  },
  {
    id: "3",
    name: "Wayanad",
    slug: "wayanad",
    image: destinationImage("wayanad"),
    description: "Wildlife, waterfalls, and tribal heritage",
    guideCount: 15,
    highlights: ["Edakkal Caves", "Chembra Peak", "Wildlife Safari"],
  },
  {
    id: "4",
    name: "Varkala",
    slug: "varkala",
    image: destinationImage("varkala"),
    description: "Cliff-side beaches and Ayurvedic retreats",
    guideCount: 12,
    highlights: ["Cliff Beach", "Janardhana Temple", "Surfing"],
  },
  {
    id: "5",
    name: "Vagamon",
    slug: "vagamon",
    image: destinationImage("vagamon"),
    description: "Pine forests, meadows, and paragliding",
    guideCount: 9,
    highlights: ["Pine Valley", "Paragliding", "Meadows"],
  },
  {
    id: "6",
    name: "Athirapally",
    slug: "athirapally",
    image: destinationImage("athirapally"),
    description: "The Niagara of India — thundering waterfalls",
    guideCount: 8,
    highlights: ["Athirapally Falls", "Vazhachal", "Jungle Trek"],
  },
];

export const guides: Guide[] = [
  {
    id: "g1",
    name: "Arun Nair",
    slug: "arun-nair",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
    coverImage: destinationImage("trivandrum"),
    location: "Trivandrum, Kerala",
    destinationSlug: "trivandrum",
    languages: ["Malayalam", "English", "Hindi"],
    experienceYears: 8,
    rating: 4.9,
    reviewCount: 127,
    specializations: ["Cultural Tours", "Temple Walks", "Food Trails"],
    pricePerDay: 2500,
    verified: true,
    bio: "Born and raised in Trivandrum, I know every hidden lane, temple story, and street food spot. Let me show you Kerala's capital through local eyes.",
    services: [
      { id: "s1", name: "Temple & Heritage Walk", price: 1200, duration: "Half day", description: "Padmanabhaswamy and old city exploration" },
      { id: "s2", name: "Kovalam Sunset Tour", price: 1800, duration: "Half day", description: "Beach hopping with local seafood lunch" },
      { id: "s3", name: "Full Day Trivandrum Explorer", price: 3500, duration: "Full day", description: "Complete city experience with transport" },
    ],
    certifications: ["Kerala Tourism Certified Guide", "First Aid Certified"],
    gallery: [
      "https://images.unsplash.com/photo-1585139226532-8751d7d6b272?w=600&q=80",
      "https://images.unsplash.com/photo-1593693397690-362cb7be786c?w=600&q=80",
      "https://images.unsplash.com/photo-1548013146-72479768bada?w=600&q=80",
    ],
    itinerary: [
      { time: "8 AM", activity: "Padmanabhaswamy Temple visit" },
      { time: "11 AM", activity: "Local market & spice bazaar" },
      { time: "1 PM", activity: "Authentic Sadya lunch" },
      { time: "4 PM", activity: "Kovalam beach sunset" },
    ],
  },
  {
    id: "g2",
    name: "Meera Thomas",
    slug: "meera-thomas",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
    coverImage: destinationImage("munnar"),
    location: "Munnar, Kerala",
    destinationSlug: "munnar",
    languages: ["Malayalam", "English", "Tamil"],
    experienceYears: 6,
    rating: 4.8,
    reviewCount: 89,
    specializations: ["Trekking", "Tea Plantation", "Photography"],
    pricePerDay: 2200,
    verified: true,
    bio: "Tea estate daughter turned adventure guide. I'll take you beyond tourist spots to secret viewpoints and hidden waterfalls.",
    services: [
      { id: "s4", name: "Sunrise Trek", price: 1500, duration: "Half day", description: "Early morning peak trek with breakfast" },
      { id: "s5", name: "Tea Plantation Tour", price: 1000, duration: "3 hours", description: "Walk through estates with tasting session" },
      { id: "s6", name: "Photography Tour", price: 2000, duration: "Full day", description: "Best spots for landscape photography" },
    ],
    certifications: ["Wildlife Guide License", "Mountain Rescue Trained"],
    gallery: [...keralaImages.guides.gallery],
    itinerary: [
      { time: "6 AM", activity: "Sunrise at Top Station" },
      { time: "9 AM", activity: "Tea plantation walk" },
      { time: "12 PM", activity: "Hidden waterfall trek" },
      { time: "3 PM", activity: "Local tea tasting" },
    ],
  },
  {
    id: "g3",
    name: "Rahul Menon",
    slug: "rahul-menon",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&q=80",
    coverImage: destinationImage("wayanad"),
    location: "Wayanad, Kerala",
    destinationSlug: "wayanad",
    languages: ["Malayalam", "English", "Hindi", "French"],
    experienceYears: 10,
    rating: 4.95,
    reviewCount: 156,
    specializations: ["Wildlife", "Camping", "Tribal Culture"],
    pricePerDay: 3000,
    verified: true,
    bio: "Decade of guiding through Wayanad's jungles. From Chembra Peak to tribal villages — authentic wilderness experiences.",
    services: [
      { id: "s7", name: "Chembra Peak Trek", price: 2000, duration: "Full day", description: "Heart-shaped lake trek with camping option" },
      { id: "s8", name: "Wildlife Safari Guide", price: 2500, duration: "Full day", description: "Expert wildlife spotting in sanctuaries" },
      { id: "s9", name: "Camping Package", price: 4500, duration: "2 days", description: "Overnight camping with meals included" },
    ],
    certifications: ["Forest Department Licensed", "Wildlife Expert"],
    gallery: [
      "https://images.unsplash.com/photo-1580619305218-8423a4a6548c?w=600&q=80",
      "https://images.unsplash.com/photo-1441974231530-c3367fd5b0e3?w=600&q=80",
    ],
    itinerary: [
      { time: "7 AM", activity: "Forest entry & bird watching" },
      { time: "10 AM", activity: "Tribal village experience" },
      { time: "1 PM", activity: "Traditional lunch" },
      { time: "4 PM", activity: "Waterfall & sunset point" },
    ],
  },
  {
    id: "g4",
    name: "Priya Krishnan",
    slug: "priya-krishnan",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=80",
    coverImage: destinationImage("varkala"),
    location: "Trivandrum, Kerala",
    destinationSlug: "trivandrum",
    languages: ["Malayalam", "English", "Arabic"],
    experienceYears: 5,
    rating: 4.7,
    reviewCount: 64,
    specializations: ["Beach Tours", "Ayurveda", "Yoga Retreats"],
    pricePerDay: 2000,
    verified: true,
    bio: "Varkala cliff expert and wellness enthusiast. Perfect for families and solo travelers seeking calm coastal experiences.",
    services: [
      { id: "s10", name: "Varkala Cliff Walk", price: 1500, duration: "Half day", description: "Cliff path with Ayurvedic spa stop" },
      { id: "s11", name: "Beach & Yoga Morning", price: 1200, duration: "4 hours", description: "Sunrise yoga followed by beach breakfast" },
    ],
    certifications: ["Yoga Instructor", "Ayurveda Wellness Guide"],
    gallery: [
      "https://images.unsplash.com/photo-1585139226532-8751d7d6b272?w=600&q=80",
    ],
    itinerary: [
      { time: "6 AM", activity: "Sunrise yoga on cliff" },
      { time: "9 AM", activity: "Ayurvedic breakfast" },
      { time: "11 AM", activity: "Beach exploration" },
      { time: "2 PM", activity: "Spa & relaxation" },
    ],
  },
  {
    id: "g5",
    name: "Vishnu Das",
    slug: "vishnu-das",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80",
    coverImage: destinationImage("trivandrum"),
    location: "Trivandrum, Kerala",
    destinationSlug: "trivandrum",
    languages: ["Malayalam", "English", "German"],
    experienceYears: 7,
    rating: 4.85,
    reviewCount: 98,
    specializations: ["Adventure", "Jeep Safari", "Backwaters"],
    pricePerDay: 2800,
    verified: true,
    bio: "Adventure junkie with my own jeep fleet. Backwater cruises, off-road trails, and adrenaline-packed day trips.",
    services: [
      { id: "s12", name: "Jeep Safari", price: 3500, duration: "Full day", description: "Off-road adventure through hills and villages" },
      { id: "s13", name: "Backwater Cruise", price: 2200, duration: "Half day", description: "Private houseboat experience" },
    ],
    certifications: ["Commercial Driver License", "Boat Operator License"],
    gallery: [
      "https://images.unsplash.com/photo-1548013146-72479768bada?w=600&q=80",
    ],
    itinerary: [
      { time: "8 AM", activity: "Jeep pickup & village drive" },
      { time: "11 AM", activity: "Hidden backwater entry" },
      { time: "1 PM", activity: "Fishing village lunch" },
      { time: "4 PM", activity: "Sunset cruise" },
    ],
  },
  {
    id: "g6",
    name: "Anjali Raj",
    slug: "anjali-raj",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&q=80",
    coverImage: destinationImage("vagamon"),
    location: "Vagamon, Kerala",
    destinationSlug: "vagamon",
    languages: ["Malayalam", "English"],
    experienceYears: 4,
    rating: 4.6,
    reviewCount: 42,
    specializations: ["Paragliding", "Camping", "Nature Walks"],
    pricePerDay: 1800,
    verified: false,
    bio: "Young adventure guide passionate about Vagamon's pine forests and meadows. Great for budget travelers and groups.",
    services: [
      { id: "s14", name: "Paragliding Experience", price: 4000, duration: "Half day", description: "Tandem flight with meadow picnic" },
      { id: "s15", name: "Pine Forest Trek", price: 1000, duration: "4 hours", description: "Guided walk through pine valleys" },
    ],
    certifications: ["Adventure Sports Basic"],
    gallery: [
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
    ],
    itinerary: [
      { time: "7 AM", activity: "Meadow sunrise walk" },
      { time: "10 AM", activity: "Pine forest exploration" },
      { time: "1 PM", activity: "Campfire lunch" },
      { time: "3 PM", activity: "Paragliding session" },
    ],
  },
];

export const reviews: Review[] = [
  { id: "r1", author: "Sarah M.", rating: 5, comment: "Arun showed us places no guidebook mentions. The Sadya lunch was unforgettable!", date: "2025-11-12" },
  { id: "r2", author: "James K.", rating: 5, comment: "Meera's sunrise trek was the highlight of our Kerala trip. Highly recommend.", date: "2025-10-28" },
  { id: "r3", author: "Priya S.", rating: 4, comment: "Great experience overall. Rahul's wildlife knowledge is incredible.", date: "2025-10-15" },
];

/** Sample open trip requests visible to guides in an area */
export const tripRequests: TripRequest[] = [
  {
    id: "tr1",
    customerName: "Rahul S.",
    destination: "Trivandrum",
    destinationSlug: "trivandrum",
    duration: 2,
    budget: 5000,
    groupSize: 4,
    interests: ["Nature", "Local Food", "Temples"],
    travelStyle: "Relaxed",
    description: "Looking for hidden places and authentic local food. Family with 2 kids.",
    status: "open",
    createdAt: "2026-06-20T10:30:00Z",
    bids: [
      {
        id: "b1",
        guideId: "g1",
        guideName: "Arun Nair",
        guideAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=80",
        price: 4800,
        message: "I can cover Kovalam, temple walk, and a family-friendly Sadya lunch within your budget.",
        includes: ["Transport", "Temple tour", "Local lunch", "Beach sunset"],
        status: "pending",
      },
      {
        id: "b2",
        guideId: "g5",
        guideName: "Vishnu Das",
        guideAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=80",
        price: 5200,
        message: "Slightly above budget but includes jeep safari to hidden backwater spots.",
        includes: ["Jeep safari", "Backwater cruise", "Village lunch"],
        status: "pending",
      },
    ],
  },
  {
    id: "tr2",
    customerName: "Emma W.",
    destination: "Munnar",
    destinationSlug: "munnar",
    duration: 3,
    budget: 10000,
    groupSize: 2,
    interests: ["Trekking", "Photography", "Tea Gardens"],
    travelStyle: "Adventure",
    description: "Need hidden places and sunrise viewpoints. We're photographers!",
    status: "bidding",
    createdAt: "2026-06-19T14:00:00Z",
    bids: [
      {
        id: "b3",
        guideId: "g2",
        guideName: "Meera Thomas",
        guideAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&q=80",
        price: 8500,
        message: "3-day photography trek with secret viewpoints and tea estate access.",
        includes: ["Sunrise treks", "Tea plantation", "Photography assistance", "Breakfast"],
        status: "pending",
      },
    ],
  },
  {
    id: "tr3",
    customerName: "David L.",
    destination: "Trivandrum",
    destinationSlug: "trivandrum",
    duration: 1,
    budget: 3000,
    groupSize: 2,
    interests: ["Beach", "Ayurveda"],
    travelStyle: "Wellness",
    description: "Half day Varkala cliff experience with spa recommendation.",
    status: "open",
    createdAt: "2026-06-22T08:00:00Z",
    bids: [],
  },
];

export function getDestinationBySlug(slug: string): Destination | undefined {
  return destinations.find((d) => d.slug === slug);
}

export function getGuidesByDestination(slug: string): Guide[] {
  return guides.filter((g) => g.destinationSlug === slug);
}

export function getGuideById(id: string): Guide | undefined {
  return guides.find((g) => g.id === id || g.slug === id);
}

export function getTripRequestsByDestination(slug: string): TripRequest[] {
  return tripRequests.filter((r) => r.destinationSlug === slug);
}
